-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 20, 2026 at 04:56 PM
-- Server version: 8.0.46
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `projekt_pwa`
--
CREATE DATABASE IF NOT EXISTS `projekt_pwa` DEFAULT CHARACTER SET cp1250 COLLATE cp1250_croatian_ci;
USE `projekt_pwa`;

-- --------------------------------------------------------

--
-- Table structure for table `korisnik`
--

CREATE TABLE `korisnik` (
  `id` int NOT NULL,
  `ime` varchar(32) COLLATE utf8mb4_croatian_ci NOT NULL,
  `prezime` varchar(32) COLLATE utf8mb4_croatian_ci NOT NULL,
  `korisnicko_ime` varchar(32) COLLATE utf8mb4_croatian_ci NOT NULL,
  `lozinka` varchar(255) COLLATE utf8mb4_croatian_ci NOT NULL,
  `razina` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_croatian_ci;

--
-- Dumping data for table `korisnik`
--

INSERT INTO `korisnik` (`id`, `ime`, `prezime`, `korisnicko_ime`, `lozinka`, `razina`) VALUES
(1, 'Filip', 'Poljak', 'fpoljak', '$2y$10$knS9Wy6VrKF/WSR68KL1x.qYOcKiMA9rLpA2.UcuiKpAZq5Eg2khG', 0),
(3, 'ad', 'min', 'admin', '$2y$10$UJqSPR0n.yuQ/0kT/IQNyu4xkqIgrHddCeEO0yT2I8Wsy.fYI2d0G', 1);

-- --------------------------------------------------------

--
-- Table structure for table `vijesti`
--

CREATE TABLE `vijesti` (
  `id` int NOT NULL,
  `datum` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `naslov` varchar(255) COLLATE utf8mb4_croatian_ci NOT NULL,
  `sazetak` text CHARACTER SET utf8mb4 COLLATE utf8mb4_croatian_ci NOT NULL,
  `tekst` text CHARACTER SET utf8mb4 COLLATE utf8mb4_croatian_ci NOT NULL,
  `slika` varchar(64) COLLATE utf8mb4_croatian_ci NOT NULL,
  `kategorija` varchar(64) COLLATE utf8mb4_croatian_ci NOT NULL,
  `arhiva` tinyint(1) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_croatian_ci;

--
-- Dumping data for table `vijesti`
--

INSERT INTO `vijesti` (`id`, `datum`, `naslov`, `sazetak`, `tekst`, `slika`, `kategorija`, `arhiva`) VALUES
(1, '2026-06-12 10:21:20', '\"Je vis sur la route, mais sans concert au bout\" : on a passe une journee avec Francis Lalanne, tete de liste \"gilets jaunes\" aux europeennes', 'Le chanteur mene une campagne atypique pour les elections, marquee par une precarite revendiquee et un discours anti-systeme radical.', 'Dans le cadre des elections europeennes, le chanteur Francis Lalanne, engage depuis plusieurs annees aux cotes des \"gilets jaunes\", s\'est lance dans la course aux suffrages avec une liste resolument contestataire. Loin des meetings traditionnels et des grands budgets des partis traditionnels, il parcourt la France en nomade pour convaincre les electeurs de s\'opposer aux institutions de Bruxelles.\r\n\r\nSuite a un premier bilan de campagne effectue par les observateurs, pour le moment, cette liste peine a decoller dans les sondages, revele franceinfo vendredi 17 mai. Parmi les candidats issus de la societe civile qui l\'accompagnent, on retrouve des figures locales du mouvement des ronds-points. Aucun grand parti traditionnel n\'a souhaite s\'allier avec sa demarche. Or, ces mouvements contestataires representent pourtant une part non negligeable de l\'electorat indécis.\r\n\r\n<h3>\"Encore des coleres a rassembler\"</h3>\r\n\r\nDans sa reponse aux critiques, Francis Lalanne, tete de liste, exprime des \"desaccords de fond\" avec le systeme politique actuel. Sa liste, non alignee sur les partis officiels, parle neanmoins d\'un soutien de principe a la democratie directe et au referendum d\'initiative citoyenne. Ce sont \"des citoyens qui n\'ont pas toujours ete entendus sur ces questions\" affirme sur franceinfo un politologue qui suit la campagne. \"Et ce, soit pour des raisons liees a la defiance envers l\'Union europeenne, soit liees au souhait de privilégier finalement l\'action de terrain.\"\r\n\r\nToutefois, \"le combat vaut la peine d\'etre mene\" estime le candidat. Sur l\'ensemble des electeurs potentiels, une minorite se dit prete a voter pour lui. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, un sondage realise aupres de la population revele que la majorite des Francais partagent la colere sociale exprimee par le mouvement, meme si l\'alternative politique proposee par cette liste divise fortement les citoyens.', 'gilets.jpg', 'elections', 0),
(9, '2026-06-20 11:33:01', 'INFO FRANCEINFO. Europeennes : les Republicains et le RN n\'ont pas signe le plaidoyer de Transparency International pour la lutte contre la corruption', '149 candidats francais d\'autres partis l\'ont signe, dont sept tetes de listes, selon l\'ONG.', 'Dans le cadre des elections europeennes, l\'ONG Transparency International, qui lutte contre la corruption, a invite tous les candidats a signer un plaidoyer afin qu\'ils s\'engagent a proteger l\'Etat de droit, a lutter contre l\'evasion fiscale et a ameliorer la transparence des institutions europeennes.\r\n\r\nSuite a un premier bilan effectue par l\'ONG, pour le moment, 149 candidats aux elections europeennes en France ont signe ce plaidoyer, revele franceinfo vendredi 17 mai. Parmi ces candidats qui s\'engagent, on retrouve sept tetes de liste aux europeennes (La France insoumise, Renaissance, Parti communiste, Europe Ecologie-Les Verts, Debout la France, Envie d\'Europe et Parti Pirate). Aucun candidat des listes du Rassemblement national et des Republicains n\'a signe. Or, ces deux listes regroupent a elles seules 40% des candidats en position eligible.\r\n\r\n<h3>\"Encore des gens a convaincre\"</h3>\r\n\r\nDans sa reponse a l\'ONG, Jordan Bardella, tete de liste RN, exprime des \"desaccords de fond\" avec les propositions de l\'ONG. La liste Les Republicains, elle aussi non signataire du plaidoyer, parle neanmoins d\'un soutien de principe a la deontologie et a l\'Etat de droit. Ce sont \"des partis qui n\'ont pas toujours ete engages sur ces questions\" affirme sur franceinfo Marc-Andre Feffer, le president de l\'ONG Transparency International. \"Et ce, soit pour des raisons liees a l\'Union europeenne, soit liees au souhait de privilégier finalement la deontologie individuelle.\"\r\n\r\nToutefois, \"le verre est plus qu\'a moitie plein\" estime Marc-Andre Feffer. Sur les 2 686 candidats aux europeennes, 149 ont signe le plaidoyer. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, l\'ONG Transparency International a realise un sondage aupres de la population qui revele que 88% des Francais jugent prioritaire le renforcement de l\'ethique et de la transparence dans les institutions europeennes.', 'parliament.jpg', 'elections', 0),
(10, '2026-06-20 11:37:56', 'Italie : Matteo Salvini affaibli pour les europennes', 'Le chef de la Ligue fait face a une baisse de popularite et a des divisions internes qui menacent son influence au sein du Parlement europeen.', 'Dans le cadre des elections europeennes, Matteo Salvini, le leader de la Ligue en Italie, traverse une periode de fortes turbulences politiques. Connu pour ses positions souverainistes et anti-immigration, l\'actuel ministre des Transports tente de remobiliser sa base electorale alors que son parti subit la concurrence directe de ses allies de coalition au gouvernement italien.\r\n\r\nSuite a un premier bilan des intentions de vote effectue par les instituts de sondage, pour le moment, la Ligue est en net recul par rapport a son score historique de 2019, revele franceinfo vendredi 17 mai. Parmi les candidats de la droite nationaliste qui s\'engagent, on observe une reconfiguration des forces au profit de Fratelli d\'Italia. Aucun signe de rapprochement n\'est envisage avec les partis centristes. Or, ces deux formations de droite regroupent a elles seules une part determinante des eurodeputes italiens en position eligible.\r\n\r\n<h3>\"Encore des electeurs a reconquerir\"</h3>\r\n\r\nDans sa reponse aux medias, Matteo Salvini, tete de file de son parti, exprime des \"desaccords de fond\" avec la politique actuelle de la Commission europeenne. La Ligue, bien que fragilisee, parle neanmoins d\'un soutien de principe a la souverainete des Etats et au controle strict des frontieres. Ce sont \"des partis qui n\'ont pas toujours ete constants sur leurs strategies europeennes\" affirme sur franceinfo un correspondant a Rome. \"Et ce, soit pour des raisons liees a la gouvernance de l\'Union europeenne, soit liees au souhait de privilégier finalement les interets nationaux.\"\r\n\r\nToutefois, \"la campagne est loin d\'etre terminee\" estime l\'entourage de Matteo Salvini. Sur l\'ensemble des votants en Italie, une part importante reste indecise. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, un sondage realise aupres de la population italienne revele que les preoccupations economiques et le pouvoir d\'achat restent prioritaires, devancant les debats ideologiques traditionnels sur l\'avenir des institutions europeennes.', 'salvini.jpg', 'elections', 0),
(11, '2026-06-20 11:39:23', '\"Nous avons une capacite a nous adresser a des Francais qui viennet d\'horizons tres differents\", assure Nicolas Bay du Rassemblement national', 'Le parti de Marine Le Pen mise sur une strategie de rassemblement large et transpartisan pour consolider sa position en vue du scrutin europeen.', 'Dans le cadre des elections europeennes, Nicolas Bay, l\'un des cadres du Rassemblement national, affiche une confiance marquee quant a la portee du message de son mouvement. Loin de se cantonner a son electorat traditionnel, le parti cherche a attirer des deçus de la droite comme de la gauche en mettant en avant les themes de la souverainete nationale et de la protection economique face aux directives de Bruxelles.\r\n\r\nSuite a un premier bilan des forces en presence effectue par les analystes, pour le moment, cette strategie de dedabolisation porte ses fruits dans les intentions de vote, revele franceinfo vendredi 17 mai. Parmi les profils de candidats qui s\'engagent sur la liste, on retrouve des profils varies issus de la fonction publique, du secteur prive et de la societe civile. Aucun accord officiel n\'a cependant ete passe avec d\'autres formations politiques majeures. Or, cette liste regroupe a elle seule une part considerable des intentions de vote chez les electeurs dejas decides.\r\n\r\n<h3>\"Encore des electeurs a convaincre\"</h3>\r\n\r\nDans sa reponse aux critiques de ses adversaires, Nicolas Bay exprime des \"desaccords de fond\" avec la vision federaliste de la Commission europeenne. Le Rassemblement national, bien que boycotte par une partie de la classe politique, parle neanmoins d\'un soutien de principe a la cooperation des nations et a la defense de l\'identite culturelle. Ce sont \"des electeurs qui n\'ont pas toujours ete rassembles sous une meme banniere\" affirme sur franceinfo un politologue invite en plateau. \"Et ce, soit pour des raisons liees a la gestion de l\'Union europeenne, soit liees au souhait de privilégier finalement un protectionnisme local.\"\r\n\r\nToutefois, \"la dynamique est de notre cote\" estime Nicolas Bay. Sur l\'ensemble du corps electoral français, une part significative de la population reste a seduire avant le jour du vote. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, un sondage realise aupres de la population revele que la diversite de l\'electorat potentiel du parti s\'accroit, touchant desormais des categories socio-professionnelles tres variees qui placent la securite et le pouvoir d\'achat au cœur de leurs priorites pour les institutions europeennes.', 'nicolasbay.jpg', 'elections', 0),
(12, '2026-06-20 11:41:09', '80 km/h, PMA, chomage, europeennes... Ce qu\'il faut retenir de l\'interview d\'Edouard Philippe sur franceinfo', 'Le Premier ministre a balaie l\'actualite politique et sociale, defendu le bilan du gouvernement et fixe les caps a l\'approche du scrutin europeen.', 'Dans le cadre des elections europeennes, le Premier ministre Edouard Philippe a accorde un entretien exclusif pour clarifier la feuille de route de la majorite face aux defis actuels. Entre la contestation sociale, les reformes de societe comme la PMA et les debats ecologiques incarnes par la limitation a 80 km/h, le chef du gouvernement tente de rassurer les citoyens et de remobiliser son camp face a la montee des oppositions.\r\n\r\nSuite a un premier bilan des reformes menees par l\'executif, pour le moment, les resultats sur le chomage affichent une legere amelioration, revele franceinfo vendredi 17 mai. Parmi les mesures qui s\'engagent, on retrouve des simplifications pour les entreprises et des incitations au retour a l\'emploi. Aucun recul majeur n\'est envisage sur la trajectoire budgetaire malgre les demandes de l\'opposition. Or, ces dossiers economiques et sociaux regroupent a eux seuls les principales attentes des electeurs de la majorite presidentielle.\r\n\r\n<h3>\"Encore des sceptiques a convaincre\"</h3>\r\n\r\nDans sa reponse aux critiques, Edouard Philippe exprime des \"desaccords de fond\" avec les propositions des partis rivaux sur l\'avenir de l\'Europe. La majorite, bien que bousculee par les mouvements sociaux, parle neanmoins d\'un soutien de principe au projet europeen et au renforcement de la zone euro. Ce sont \"des réformes qui n\'ont pas toujours ete simples a mettre en œuvre\" affirme sur franceinfo un conseiller de Matignon apres l\'emission. \"Et ce, soit pour des raisons liees a la conjoncture de l\'Union europeenne, soit liees au souhait de privilégier finalement la stabilite institutionnelle.\"\r\n\r\nToutefois, \"le cap reste fermement maintenu\" estime le Premier ministre. Sur les nombreux chantiers lances depuis le debut du quinquennat, une partie commence a porter ses fruits. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, un sondage realise aupres de la population revele que les questions liees au pouvoir d\'achat, au chomage et a la justice fiscale restent prioritaires pour une large majorite de Francais, qui attendent des engagements clairs de la part des candidats pour les institutions europeennes.', 'edouard.jpg', 'elections', 0),
(13, '2026-06-20 11:41:37', 'JT de 8h du vendredi 17 mai 2019', 'Retrouvez l\'essentiel de l\'actualite de ce debut de journee, marque par les derniers rebondissements des europeennes et les grands dossiers economiques.', 'Dans le cadre des rendez-vous d\'information de franceinfo, l\'edition du journal de 8 heures de ce vendredi a passe en revue les sujets brulants nationaux et internationaux. Loin des longs debats de la veille, cette session matinale s\'est concentree sur les annonces gouvernementales urgentes et la derniere ligne droite de la campagne pour le scrutin de Bruxelles.\r\n\r\nSuite a un premier bilan des actualites de la matinee, pour le moment, les sujets lies au pouvoir d\'achat et a la mobilisaton sociale restent au cœur des reportages, revele franceinfo vendredi 17 mai. Parmi les sequences qui s\'engagent dans ce journal, on retrouve un focus sur la situation de l\'emploi et un point complet sur les listes en presence (La France insoumise, Renaissance, Parti communiste, Europe Ecologie-Les Verts). Aucun grand titre de l\'actualite n\'a ete oublie par la redaction. Or, ces sujets de societe regroupent a eux seuls plus de 40% des preoccupations des telespectateurs.\r\n\r\nDans sa reponse aux questions de la redaction, l\'invite du matin exprime des \"desaccords de fond\" avec la politique economique actuelle. La direction du journal, elle aussi attentive a la diversite des opinions, parle neanmoins d\'un soutien de principe au pluralisme et au decryptage de l\'actualite. Ce sont \"des sujets qui n\'ont pas toujours ete traites avec autant de precision\" affirme sur franceinfo le redacteur en chef a la sortie du studio. \"Et ce, soit pour des raisons liees au format court du journal, soit liees au souhait de privilégier finalement l\'actualite chaude du terrain.\"\r\n\r\nToutefois, \"le conducteur du journal est parfaitement tenu\" estime l\'equipe technique. Sur les 30 minutes consacrees a ce journal de 8 heures, une large place a ete faite aux temoignages directs. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, une etude realisee aupres du public revele que 88% des Francais jugent prioritaire le maintien d\'une information rigoureuse et transparente dans les grands journaux televises.', 'jt8h.jpg', 'les jt', 0),
(14, '2026-06-20 11:42:10', 'Le JT de 7h de franceinfo du vendredi 17 mai 2019 ', 'Suivez les premiers flashs d\'information de la matinale, entre depeches de derniere minute et developpements sur la campagne des europeennes.', 'Dans le cadre des sessions matinales d\'information de franceinfo, l\'edition de 7 heures a donne le coup d\'envoi des actualites du jour. Conçu pour offrir un tour d\'horizon rapide avant le debut de la journee de travail, ce journal televise s\'est focalise sur les declarations politiques de la nuit et les previsions economiques majeures pour la France et ses voisins europeens.\r\n\r\nSuite a un premier bilan des sujets developpes a l\'antenne, pour le moment, les annonces sur l\'emploi et la conjoncture nationale ouvrent les titres, revele franceinfo vendredi 17 mai. Parmi les reportages qui s\'engagent dans cette premiere edition, on retrouve un point sur les deplacements des candidats (La France insoumise, Renaissance, Parti communiste, Europe Ecologie-Les Verts) et un decryptage des enjeux de depeches internationales. Aucun evenement majeur de la nuit n\'a echappe aux equipes de la redaction. Or, ces dossiers prioritaires regroupent a eux seuls une part essentielle des attentes du public au reveil.\r\n\r\nDans sa reponse aux sollicitations de nos reporters, l\'analyse politique du matin exprime des \"desaccords de fond\" avec la lecture habituelle des donnees de campagne. La redaction du journal, fidele a sa ligne editoriale, parle neanmoins d\'un soutien de principe a l\'objectivite et a l\'explication des faits. Ce sont \"des thematiques qui n\'ont pas toujours ete analysees sous cet angle en debut de journee\" affirme sur franceinfo un chef de cabine a la fin du direct. \"Et ce, soit pour des raisons liees au rythme tres soutenu de la matinale, soit liees au souhait de privilégier finalement les images brutes du terrain.\"\r\n\r\nToutefois, \"le premier grand direct est une reussite\" estime l\'equipe de presentation. Sur le volume total d\'informations traitees a 7 heures, les sujets de proximite restent dominants. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, une enquete menee aupres de l\'audience revele que la majorite des Francais jugent prioritaire de disposer d\'un decryptage clair et rapide de l\'actualite dès les premieres heures de la matinee.', 'jt7h.jpg', 'les jt', 0),
(15, '2026-06-20 11:42:34', 'Grand Soir 3 du jeudi 16 mai 2019', 'Le grand rendez-vous d\'information de la fin de journee revient sur les moments cles de l\'actualite politique, economique et europeenne.', 'Dans le cadre des sessions nocturnes d\'information de franceinfo, l\'edition du Grand Soir 3 a propose un bilan complet des evenements marquants de la journee. Conçu pour offrir une analyse approfondie et prendre le temps du debat, ce journal televise s\'est focalise sur les derniers ajustements des candidats a l\'approche du scrutin et les grands enjeux sociitaux de la semaine.\r\n\r\nSuite a un premier bilan des dossiers developpes en plateau, pour le moment, les questions liees a la politique interieure et aux dynamiques continentales ouvrent les discussions, revele franceinfo vendredi 17 mai. Parmi les reportages qui s\'engagent dans cette edition tardive, on retrouve un eclairage sur les strategies des principales forces politiques (La France insoumise, Renaissance, Parti communiste, Europe Ecologie-Les Verts) et un debat avec des experts en studio. Aucun grand debrief de la journee n\'a ete omis par la redaction. Or, ces analyses de fond regroupent a elles seules une part essentielle des attentes du public en fin de soiree.\r\n\r\nDans sa reponse aux interrogations de nos journalistes, l\'invite du soir exprime des \"desaccords de fond\" avec les orientations proposees par ses contradicteurs. La redaction du journal, fidele a sa mission d\'information, parle neanmoins d\'un soutien de principe au pluralisme et a la confrontation constructive des idees. Ce sont \"des problematiques qui n\'ont pas toujours ete abordees avec autant de recul au cours de la journee\" affirme sur franceinfo un redacteur en chef a la fin de l\'enregistrement. \"Et ce, soit pour des raisons liees au format plus analytique de la tranche nocturne, soit liees au souhait de privilégier finalement les grands enjeux de long terme.\"\r\n\r\nToutefois, \"le debat a permis d\'eclairer les choix des electeurs\" estime l\'equipe de production. Sur l\'ensemble du temps consacre a cette grande edition, les sequences d\'explication restent dominantes. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, une etude realisee aupres des telespectateurs revele que la majorite des Francais jugent prioritaire de disposer d\'un espace de debats et d\'analyses poussees en toute fin de journee pour mieux comprendre l\'actualite nationale et europeenne.', 'grandsoir.jpg', 'les jt', 0),
(16, '2026-06-20 11:42:58', 'JT de 20h du jeudi 16 mai 2019', 'La grande edition de la mi-soiree propose un retour complet sur l\'actualite marquante du jour, de la scene nationale aux enjeux internationaux.', 'Dans le cadre des rendez-vous d\'information incontournables de franceinfo, l\'edition du journal de 20 heures a livre une analyse detaillee des evenements majeurs de la journee. Conçu pour offrir une synthese exhaustive et des reportages grand format, ce journal televise s\'est focalise sur les decisions economiques fortes du gouvernement et les deplacements strategiques des candidats a l\'approche des echeances majeures.\r\n\r\nSuite a un premier bilan des sujets developpes au cours du journal, pour le moment, les enquetes sur le terrain et les preoccupations citoyennes restent au premier plan, revele franceinfo vendredi 17 mai. Parmi les grands dossiers qui s\'engagent dans cette edition, on retrouve un eclairage sur la situation sociale et un panorama des forces politiques en presence (La France insoumise, Renaissance, Parti communiste, Europe Ecologie-Les Verts). Aucun fait marquant de l\'actualite n\'a ete laisse de cote. Or, ces themes de societe regroupent a eux seuls une part preponderante des attentes des telespectateurs a cette heure de grande ecoute.\r\n\r\nDans sa reponse aux questions posees en plateau, l\'invite de la redaction exprime des \"desaccords de fond\" avec les analyses presentees par ses opposants politiques. La direction de l\'information, soucieuse d\'equilibre, parle neanmoins d\'un soutien de principe a la mise en perspective des faits et au pluralisme des expressions. Ce sont \"des problematiques qui n\'ont pas toujours ete traitees avec autant de relief\" affirme sur franceinfo un chef de l\'information a la sortie du plateau. \"Et ce, soit pour des raisons liees au format plus developpe de l\'edition de 20 heures, soit liees au souhait de privilégier finalement les temoignages et le grand format.\"\r\n\r\nToutefois, \"la coherence de l\'edition est pleinement assuree\" estime l\'equipe de redaction. Sur la totalite de ce journal de 20 heures, les enquetes approfondies restent l\'element central. \"Ceux qui ont repondu positivement nous aident beaucoup. Il y a encore des gens a convaincre, nous souhaitons qu\'il y ait un effet de masse critique sur ces questions-la.\"\r\n\r\nCourant mai, un barometre realise aupres de la population revele que la grande majorite des Francais jugent prioritaire de disposer d\'un journal de grande ecoute qui prend le temps de verifier et de decrypter l\'information face aux defis actuels.', 'jt20h.jpg', 'les jt', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `korisnik`
--
ALTER TABLE `korisnik`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `kor_ime` (`korisnicko_ime`);

--
-- Indexes for table `vijesti`
--
ALTER TABLE `vijesti`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `korisnik`
--
ALTER TABLE `korisnik`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `vijesti`
--
ALTER TABLE `vijesti`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
